kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - mkdir example
  - touch example/file.txt
  - echo "1" > example/file.txt
  - cat example/file.txt
  - curl www.solidrundev.com/filefile.php
